### PR TITLE
add target and shared scheme

### PR DESCRIPTION
**Pull request by micap**
Adding another target 'TOWebViewControllerKit' with accompanying shared scheme for Carthage support. Happy to change the target name if needed.

### CODE REVIEW

**Comment by TimOliver** [comment]
Thanks a lot for that Mica!

Umm, is appending 'Kit' really appropriate for what is ostensibly a single view controller? Is that normal Carthage conventions?

**Comment by micap** [comment]
Yea, get your point hence discussion is open. Other frameworks are UIKit, MapKit. I just didn't want to call it TOWebViewControllerFramework because the extension is '.framework'. We can keep it as TOWebViewController. Just need to have an umbrella header not collide with TOWebViewController, maybe TOWebViewControllerUmbrella.h? 



—

**Comment by micap** [comment]
For considering Apple chose these two names: SafariServices, WebKit



—

**Comment by TimOliver** [comment]
Oh cool. Thanks a lot for that. :)

Yeah, I think in this particular case, it would be appropriate to just call it `TOWebViewController.framework`, but you're right in that that might not be possible?

Ahh good point about the umbrella header. I don't suppose you can just add the framework definitions at the top of the main header can you? 

`#import <TOWebViewController/TOWebViewController.h>` would be my absolute favourite. :)

**Pull request closed without merging**
